#!/bin/bash
# sudo apt-get update 
# sudo apt-get upgrade 

yes | sudo apt-get install curl openssh-server apt-transport-https ca-certificates gnupg2 software-properties-common 
# sudo apt-get update 
# sudo apt-get upgrade 
sudo curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add - 
add-apt-repository "deb [arch=amd64] http://download.docker.com/linux/debian $(lsb_release -cs) stable"  
yes | sudo apt-get update 
yes | apt install docker-ce