#!/bin/bash
sudo apt-get update 
sudo apt-get upgrade 
sudo apt-get install openssh-server
sudo apt-get update 
sudo apt-get upgrade 
sudo apt-get install apt-transport-https ca-certificates curl gnupg2 software-properties-common 
curl -fsSL https://download.docker.com/linux/debian/gpg 
sudo apt-key add - 
add-apt-repository "deb [arch=amd64] http://download.docker.com/linux/debian $(lsb_release -cs) stable"  
sudo apt-get update 
apt install docker-ce